### ISSUE TITLE
Add auto reading time estimation

### ISSUE THREAD

**Issue by eerFun** [P0WEX/Gesko#11]
I think it would be great if the reading time calculated automatically. I've just added this for myself and if you agree, I can create PR for this.
I considered `265 WMP` for myself rounded to ceiling. If you consider another reading speed, please let me know.
Thanks.

**Comment by P0WEX** [comment]
Sure! 
Seems a good idea!
Feel free to PR

**Comment by P0WEX** [comment]
Now added in the main branch.
Thanks!!
