### ISSUE TITLE
Changing syntax highlighting

### ISSUE THREAD

**Issue by Frityet** [P0WEX/Gesko#3]
Hello there! I have just started using this theme and I have noticed that the base syntax highlighting is very lacklustre. The language which I use the most and which will be featured the most on the site, C#, has only 3 colours, and the comment colour and the actual code have the same colour, making it look horrible. I have already tried changing the `syntax_highlighter` option in `_config.yml` to `coderay` with no dice (I added the gem to `Gemfile`, the gem seems to work there is just no difference in syntax highlighting)

Thanks!

**Comment by P0WEX** [comment]
Thank you so much for reaching out, I'll try my best to fix this asap.
If you find a solution feel free to make a PR

**Comment by P0WEX** [comment]
In the meanwhile this could work:
```
{% highlight csharp %}
/// <summary>
/// Main class of the project
/// </summary>
class Program
{
    /// <summary>
    /// Main entry point of the program
    /// </summary>
    /// <param name="args">Command line args</param>
    static void Main(string[] args)
    {
        //Do stuff
    }
}
{% endhighlight %}
```

**Comment by P0WEX** [comment]
I came up with this 2 things: 

- The easiest one is to change the rouge highlighting via [rougify ](https://github.com/rouge-ruby/rouge#command-line)
- Or manually edit the `/assets/css/syntax.css`

**Comment by Frityet** [comment]
alright, Ill try that!
